triggerOnDemandTanker(
        "tx2",
        nil,
        nil,
        nil,
        GROUP:FindByName("sea-anchor-2"):GetCoordinate()
)
triggerOnDemandTanker(
        "ar6",
        nil,
        nil,
        nil,
        GROUP:FindByName("sea-anchor-3"):GetCoordinate()
)
triggerOnDemandTanker(
        "sh3",
        nil,
        nil,
        nil,
        GROUP:FindByName("sea-anchor-4"):GetCoordinate()
)
