triggerOnDemandTanker(
        "tx3",
        nil,
        nil,
        nil,
        GROUP:FindByName("sea-anchor-2"):GetCoordinate()
)
triggerOnDemandTanker(
        "ar7",
        nil,
        nil,
        nil,
        GROUP:FindByName("sea-anchor-3"):GetCoordinate()
)
triggerOnDemandTanker(
        "sh4",
        nil,
        nil,
        nil,
        GROUP:FindByName("ground-anchor-1"):GetCoordinate()
)
