---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 12/10/2021 08:39
---
BeaconsConfig = {
    enable = false,
    name = 'My beacon',
    unitName = 'MyBeaconUnit-1',
    tacan = {
        channel = 101,
        band = 'X',
        morse = 'MBC'
    }
}
